import Head from 'next/head'
import client from "../apollo-client";
//import { gql} from '@apollo/client';

import Layout from '../components/layout'
import IndexRow from './IndexRow';
import Posts from '../graphql/posts';

export default function Home(data) {
  const items = data.blogs
//  var paginateDisp = data.display
console.log( items )  
  return (
  <Layout>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="container">
      <h1>Top111</h1>
      <hr />
      {items.map((item, index) => {
console.log(item.node);
        let category_name = ""
        return (<IndexRow key={index}
          id={item.node.postId} title={item.node.title}
          date={item.node.date} category_name={""} />       
        )
      })}      
    </div>
  </Layout>
  )
}
export const getStaticProps = async context => {
  const data:any = await client.query({
    query: Posts.getItems(),
    fetchPolicy: "network-only"
  });  
console.log(data);
  return {
    props : {
      blogs: data.data.posts.edges,
      page_items: [],
      category_items: [],
      site_name : "site-name",
      info_text : "Sample CMSの関連記事を公開予定しております。",        
      display: 0
    }
  };
}
